// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  /**
   * Trigger the OAuth flow and add a new Google account.
   */
  async addAccount(): Promise<Result<Account, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('add_account') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Remove a Google account and its stored tokens.
   */
  async removeAccount(accountId: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('remove_account', { accountId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Re-authenticate an account with expired/revoked tokens.
   * Re-runs the OAuth flow and clears the `auth_expired` flag on success.
   */
  async reauthAccount(accountId: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('reauth_account', { accountId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * List all configured accounts.
   */
  async listAccounts(): Promise<Result<Account[], string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('list_accounts') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Load the persisted theme preference. Returns `"dark"` if not set.
   */
  async loadTheme(): Promise<Result<string, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_theme') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Persist the theme preference to disk.
   */
  async saveTheme(theme: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('save_theme', { theme }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Load the persisted week start day. Returns `1` (Monday) if not set.
   */
  async loadWeekStartDay(): Promise<Result<number, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_week_start_day') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Persist the week start day to disk. 0 = Sunday, 1 = Monday.
   */
  async saveWeekStartDay(day: number): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('save_week_start_day', { day }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Load the persisted auto-mark-read preference. Returns `false` if not set.
   */
  async loadAutoMarkRead(): Promise<Result<boolean, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_auto_mark_read') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Persist the auto-mark-read preference to disk.
   */
  async saveAutoMarkRead(enabled: boolean): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('save_auto_mark_read', { enabled }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Load the persisted mail filter state. Returns `(false, false)` if not set.
   */
  async loadMailFilter(): Promise<Result<[boolean, boolean], string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_mail_filter') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Persist the mail filter state (unread, starred) to disk.
   */
  async saveMailFilter(unread: boolean, starred: boolean): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('save_mail_filter', { unread, starred }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Load the persisted calendar view mode. Returns `"week"` if not set.
   */
  async loadCalendarViewMode(): Promise<Result<string, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_calendar_view_mode') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Persist the calendar view mode to disk.
   */
  async saveCalendarViewMode(mode: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('save_calendar_view_mode', { mode }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Fetch messages for a single account and label.
   *
   * The frontend calls this once per account so results stream in as each
   * account completes independently.
   *
   * When `filter_unread` or `filter_starred` is true the corresponding Gmail
   * label is added to the `labelIds` query parameter so the API returns only
   * matching messages — not just the most recent 50.
   */
  async getAccountMessages(
    accountId: string,
    label: string,
    pageToken: string | null,
    filterUnread: boolean | null,
    filterStarred: boolean | null,
  ): Promise<Result<MessageMeta[], string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_account_messages', {
          accountId,
          label,
          pageToken,
          filterUnread,
          filterStarred,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Fetch inbox messages for the given accounts and label.
   *
   * Kept for backwards compatibility. Internally parallelises across accounts.
   */
  async getMessages(
    accountIds: string[],
    label: string,
    pageToken: string | null,
  ): Promise<Result<MessageMeta[], string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_messages', { accountIds, label, pageToken }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Fetch a full thread with message bodies.
   */
  async getThread(accountId: string, threadId: string): Promise<Result<Thread, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_thread', { accountId, threadId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Archive a thread (remove from Inbox).
   */
  async archiveThread(accountId: string, threadId: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('archive_thread', { accountId, threadId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Star or unstar a thread.
   */
  async starThread(
    accountId: string,
    threadId: string,
    starred: boolean,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('star_thread', { accountId, threadId, starred }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Mark a thread as read.
   */
  async markRead(accountId: string, threadId: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('mark_read', { accountId, threadId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Mark a thread as unread.
   */
  async markUnread(accountId: string, threadId: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('mark_unread', { accountId, threadId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Search messages across the given accounts.
   */
  async searchMessages(
    accountIds: string[],
    query: string,
  ): Promise<Result<MessageMeta[], string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('search_messages', { accountIds, query }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Send an email from the specified account.
   */
  async sendMessage(request: SendMessageRequest): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('send_message', { request }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Batch modify labels on multiple threads across accounts.
   *
   * Used by the frontend multi-select feature to perform bulk mark-read,
   * mark-unread, and archive operations.
   */
  async batchModifyThreads(
    items: BatchModifyItem[],
    addLabels: string[],
    removeLabels: string[],
  ): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('batch_modify_threads', { items, addLabels, removeLabels }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Get the total number of unread inbox threads across the given accounts.
   *
   * Uses the Gmail Labels API for accurate server-side counts instead of
   * deriving the count from the limited set of fetched messages.
   */
  async getInboxUnreadCount(accountIds: string[]): Promise<Result<number, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_inbox_unread_count', { accountIds }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * List all calendars for an account. Merges enabled state from store.
   */
  async listCalendars(accountId: string): Promise<Result<Calendar[], string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('list_calendars', { accountId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Toggle a calendar's enabled state and persist it.
   */
  async setCalendarEnabled(
    accountId: string,
    calendarId: string,
    enabled: boolean,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('set_calendar_enabled', { accountId, calendarId, enabled }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Fetch events for a single account across its enabled calendars.
   *
   * All calendar event fetches run in parallel via `tokio::task::JoinSet`.
   * The frontend calls this once per account so results stream in as each
   * account completes independently.
   */
  async getAccountEvents(
    accountId: string,
    calendarIds: string[],
    timeMin: number,
    timeMax: number,
  ): Promise<Result<CalEvent[], string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_account_events', {
          accountId,
          calendarIds,
          timeMin,
          timeMax,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Fetch events across multiple accounts and calendars for a time range.
   *
   * Kept for backwards compatibility. Internally parallelises across accounts.
   */
  async getEvents(
    accountIds: string[],
    calendarIds: string[],
    timeMin: number,
    timeMax: number,
  ): Promise<Result<CalEvent[], string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_events', { accountIds, calendarIds, timeMin, timeMax }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Create a new calendar event via Google Calendar API.
   */
  async createEvent(
    accountId: string,
    calendarId: string,
    title: string,
    start: number,
    end: number,
    allDay: boolean,
    timezone: string,
    rest: CreateEventOptionals,
  ): Promise<Result<CalEvent, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('create_event', {
          accountId,
          calendarId,
          title,
          start,
          end,
          allDay,
          timezone,
          rest,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Update an existing calendar event via Google Calendar API.
   *
   * Uses a request struct because specta supports at most 10 function parameters.
   */
  async updateEvent(
    accountId: string,
    calendarId: string,
    eventId: string,
    title: string,
    start: number,
    end: number,
    allDay: boolean,
    timezone: string,
    rest: UpdateEventOptionals,
  ): Promise<Result<CalEvent, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('update_event', {
          accountId,
          calendarId,
          eventId,
          title,
          start,
          end,
          allDay,
          timezone,
          rest,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Delete a calendar event via Google Calendar API.
   */
  async deleteEvent(
    accountId: string,
    calendarId: string,
    eventId: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('delete_event', { accountId, calendarId, eventId }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Query the Google Calendar `FreeBusy` API for guest availability.
   *
   * For each email that belongs to a connected Mogly account, queries using that
   * account's own OAuth token so we always get accurate data. Remaining external
   * emails are queried via the requesting account's token (may return no access).
   */
  async getFreebusy(
    accountId: string,
    emails: string[],
    timeMin: number,
    timeMax: number,
  ): Promise<Result<FreeBusyResult[], string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('get_freebusy', { accountId, emails, timeMin, timeMax }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Dismiss a calendar reminder: remove from backend active list and log.
   */
  async dismissReminder(eventId: string): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('dismiss_reminder', { eventId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Snooze a calendar reminder.
   *
   * Removes the event from the active list immediately (the frontend hides the
   * card right away).  After the snooze period elapses the reminder is
   * re-emitted directly — we cannot rely on the polling loop because the
   * event may have already started by then (i.e. `should_remind` returns
   * `false` for past events).
   */
  async snoozeReminder(eventId: string, snoozeMinutes: number): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('snooze_reminder', { eventId, snoozeMinutes }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Return all currently-active reminder payloads.
   * The popup window calls this on mount to retrieve reminders it may have
   * missed (its JS listener wasn't ready when the events were emitted).
   */
  async getActiveReminders(): Promise<Result<ReminderPayload[], string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_active_reminders') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Check whether OS notification permission is granted.
   */
  async isNotificationGranted(): Promise<Result<boolean, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('is_notification_granted') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Request notification permission from the OS.
   * Returns `true` if permission was granted.
   */
  async requestNotificationPermission(): Promise<Result<boolean, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('request_notification_permission') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  /**
   * Update the system tray tooltip with the current unread email count.
   */
  async setTrayBadge(count: number): Promise<Result<null, string>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('set_tray_badge', { count }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
}

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

/**
 * Account stored in JSON config.
 */
export type Account = {
  id: string
  email: string
  display_name: string
  color: string
  history_id: string
  /**
   * Whether this account's OAuth token has expired or been revoked.
   * Skipped in background sync/reminders until re-authenticated.
   */
  auth_expired?: boolean
}
export type Attachment = { id: string; filename: string; mime_type: string; size: number }
/**
 * A calendar event attendee.
 */
export type Attendee = {
  email: string
  display_name: string | null
  response_status: string | null
  is_optional: boolean
  is_organizer: boolean
  is_self: boolean
}
/**
 * Attendee input from the frontend.
 */
export type AttendeeInput = { email: string; name: string | null }
/**
 * An item in a batch modify request (account + thread pair).
 */
export type BatchModifyItem = { account_id: string; thread_id: string }
/**
 * A busy period returned by the `FreeBusy` API.
 */
export type BusyPeriod = { start: number; end: number }
/**
 * Calendar event.
 */
export type CalEvent = {
  id: string
  account_id: string
  calendar_id: string
  title: string
  start: number
  end: number
  all_day: boolean
  location: string | null
  description: string | null
  color: string | null
  conference_url: string | null
  attendees: Attendee[]
}
/**
 * A single Google Calendar within an account.
 */
export type Calendar = {
  id: string
  account_id: string
  name: string
  color: string
  enabled: boolean
  primary: boolean
}
/**
 * Optional fields for `create_event`, bundled to stay within specta's 10-param limit.
 */
export type CreateEventOptionals = {
  location: string | null
  description: string | null
  recurrence: string[] | null
  reminder_minutes: number[] | null
  attendees: AttendeeInput[] | null
}
/**
 * `FreeBusy` result for a single calendar/email.
 */
export type FreeBusyResult = {
  calendar_id: string
  busy: BusyPeriod[]
  /**
   * Whether the authenticated user has permission to view this calendar's
   * free/busy data. `false` when the Google API returns per-calendar errors
   * (e.g. `notFound`).
   */
  has_access: boolean
}
export type Message = {
  id: string
  from: string
  to: string[]
  subject: string
  body_html: string | null
  body_text: string | null
  date: number
  attachments: Attachment[]
}
/**
 * Message metadata — never stores body.
 */
export type MessageMeta = {
  id: string
  thread_id: string
  account_id: string
  from: string
  subject: string
  snippet: string
  date: number
  unread: boolean
  starred: boolean
  labels: string[]
}
/**
 * Payload emitted to the frontend when a calendar reminder fires.
 */
export type ReminderPayload = {
  event_id: string
  title: string
  start: number
  calendar_name: string
  calendar_color: string
  minutes_until: number
}
/**
 * Request payload for sending a new email.
 */
export type SendMessageRequest = {
  account_id: string
  to: string[]
  cc: string[]
  subject: string
  body: string
  in_reply_to: string | null
  references: string | null
}
/**
 * Full thread — fetched on demand.
 */
export type Thread = { id: string; account_id: string; messages: Message[] }
/**
 * Optional fields for `update_event`, bundled to stay within specta's 10-param limit.
 */
export type UpdateEventOptionals = {
  location: string | null
  description: string | null
  recurrence: string[] | null
  reminder_minutes: number[] | null
  attendees: AttendeeInput[] | null
}

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from '@tauri-apps/api/core'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow'

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E }

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>
      }
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    },
  )
}
