/**
 * Frontend type definitions matching Rust models.
 * These mirror the types auto-generated by tauri-specta in bindings.ts.
 * We define them here so components can import without depending on
 * the generated file directly (which may not exist in test environments).
 */

export interface Account {
  id: string
  email: string
  display_name: string
  color: string
  history_id: string
  auth_expired: boolean
}

export interface MessageMeta {
  id: string
  thread_id: string
  account_id: string
  from: string
  subject: string
  snippet: string
  date: number
  unread: boolean
  starred: boolean
  labels: string[]
}

export interface Thread {
  id: string
  account_id: string
  messages: Message[]
}

export interface Message {
  id: string
  from: string
  to: string[]
  subject: string
  body_html: string | null
  body_text: string | null
  date: number
  attachments: Attachment[]
}

export interface Attachment {
  id: string
  filename: string
  mime_type: string
  size: number
}

export interface Calendar {
  id: string
  account_id: string
  name: string
  color: string
  enabled: boolean
  primary: boolean
}

export interface CalEvent {
  id: string
  account_id: string
  calendar_id: string
  title: string
  start: number
  end: number
  all_day: boolean
  location: string | null
  description: string | null
  color: string | null
  conference_url: string | null
}

export interface SendMessageRequest {
  account_id: string
  to: string[]
  cc: string[]
  subject: string
  body: string
  in_reply_to?: string
  references?: string
}

export type ComposeContext =
  | { mode: 'new' }
  | {
      mode: 'reply'
      threadId: string
      accountId: string
      to: string
      subject: string
      body: string
    }
  | {
      mode: 'forward'
      threadId: string
      accountId: string
      subject: string
      body: string
    }

export interface ReminderPayload {
  event_id: string
  title: string
  start: number
  calendar_name: string
  calendar_color: string
  minutes_until: number
}

export interface ActiveReminder {
  eventId: string
  title: string
  start: number
  calendarName: string
  calendarColor: string
  minutesUntil: number
  receivedAt: number // Date.now() when the reminder was received
}

export const ACCOUNT_COLORS = [
  '#4f9cf9', // blue
  '#f97316', // orange
  '#a78bfa', // purple
  '#34d399', // green
  '#f43f5e', // rose
  '#fbbf24', // amber
] as const

export const MAIL_LABELS = [
  { id: 'INBOX', label: 'Inbox', icon: '◉' },
  { id: 'STARRED', label: 'Starred', icon: '◆' },
  { id: 'SENT', label: 'Sent', icon: '◀' },
  { id: 'DRAFT', label: 'Drafts', icon: '◧' },
  { id: 'ALL', label: 'All Mail', icon: '◈' },
  { id: 'SPAM', label: 'Spam', icon: '⊘' },
] as const
