/**
 * Frontend type definitions matching Rust models.
 * These mirror the types auto-generated by tauri-specta in bindings.ts.
 * We define them here so components can import without depending on
 * the generated file directly (which may not exist in test environments).
 */

export interface Account {
  id: string
  email: string
  display_name: string
  color: string
  history_id: string
}

export interface MessageMeta {
  id: string
  thread_id: string
  account_id: string
  from: string
  subject: string
  snippet: string
  date: number
  unread: boolean
  starred: boolean
  labels: string[]
}

export interface Thread {
  id: string
  account_id: string
  messages: Message[]
}

export interface Message {
  id: string
  from: string
  to: string[]
  subject: string
  body_html: string | null
  body_text: string | null
  date: number
  attachments: Attachment[]
}

export interface Attachment {
  id: string
  filename: string
  mime_type: string
  size: number
}

export const ACCOUNT_COLORS = [
  '#4f9cf9', // blue
  '#f97316', // orange
  '#a78bfa', // purple
  '#34d399', // green
  '#f43f5e', // rose
  '#fbbf24', // amber
] as const

export const MAIL_LABELS = [
  { id: 'INBOX', label: 'Inbox', icon: '◉' },
  { id: 'STARRED', label: 'Starred', icon: '◆' },
  { id: 'SENT', label: 'Sent', icon: '◀' },
  { id: 'DRAFT', label: 'Drafts', icon: '◧' },
  { id: 'ALL', label: 'All Mail', icon: '◈' },
  { id: 'SPAM', label: 'Spam', icon: '⊘' },
] as const
